const NUMBER_BUTTON_PRESSED = "CALCULATOR/NUMBER_BUTTON_PRESSED"
const SET_SCREEN_CONTENT = "CALCULATOR/SET_SCREEN_CONTENT"
const BUTTON_PRESSED = "CALCULATOR/BUTTON_PRESSED"
const APPEND_CHARACTER = "CALCULATOR/APPEND_CHARACTER"

export default {
    NUMBER_BUTTON_PRESSED,
    SET_SCREEN_CONTENT,
    BUTTON_PRESSED,
    APPEND_CHARACTER,
}