const NUMBER_BUTTON_PRESSED = "CALCULATOR/NUMBER_BUTTON_PRESSED"
const BUTTON_PRESSED = "CALCULATOR/BUTTON_PRESSED"
const CLEAR_SCREEN = "CALCULATOR/CLEAR_SCREEN"
const CALCULATE_ANSWER = "CALCULATOR/CALCULATE_ANSWER"
const BUTTON_CLICK_ANIMATION_STARTED = "CALCULATOR/BUTTON_CLICK_ANIMATION_STARTED"
const SAVE_ANSWER = "CALCULATOR/SAVE_ANSWER"
const SAVE_QUESTION = "CALCULATOR/SAVE_QUESTION"
const CREATE_STATEMENT = "CALCULATOR/CREATE_STATEMENT"
const TOGGLE_POWER = "CALCULATOR/TOGGLE_POWER"
const TOGGLE_SECOND_MODE = "CALCULATOR/TOGGLE_SECOND_MODE"
const TOGGLE_ALPHA_MODE = "CALCULATOR/TOGGLE_ALPHA_MODE"
const DECREMENT_PREVIOUS_QUESTION_INDEX = "CALCULATOR/DECREMENT_PREVIOUS_QUESTION_INDEX"
const INCREASE_LIST_TITLE_INDEX = "CALCULATOR/INCREASE_LIST_TITLE_INDEX"
const DECREASE_LIST_TITLE_INDEX = "CALCULATOR/DECREASE_LIST_TITLE_INDEX"

export default {
    NUMBER_BUTTON_PRESSED,
    BUTTON_PRESSED,
    CLEAR_SCREEN,
    CALCULATE_ANSWER,
    BUTTON_CLICK_ANIMATION_STARTED,
    SAVE_ANSWER,
    SAVE_QUESTION,
    CREATE_STATEMENT,
    TOGGLE_POWER,
    TOGGLE_SECOND_MODE,
    TOGGLE_ALPHA_MODE,
    DECREMENT_PREVIOUS_QUESTION_INDEX,
    INCREASE_LIST_TITLE_INDEX,
    DECREASE_LIST_TITLE_INDEX,
}