const CLEAR_LINE = "CURRENT_LINE/CLEAR_LINE"
const ADD_CHARACTER = "CURRENT_LINE/ADD_CHARACTER"
const MOVE_CURSOR_BACKWARDS = "CURRENT_LINE/MOVE_CURSOR_BACKWARDS"
const MOVE_CURSOR_FORWARDS = "CURRENT_LINE/MOVE_CURSOR_FORWARDS"

export default {
    CLEAR_LINE,
    ADD_CHARACTER,
    MOVE_CURSOR_BACKWARDS,
    MOVE_CURSOR_FORWARDS,
}